name: Build EXE and Release

on:
  push:
    tags:
      - 'v*'   # 每次推送 tag，比如 v1.0.0，自动发布 Release
  workflow_dispatch: # 也可以手动触发

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyQt6 requests urllib3 pyinstaller pillow

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --name ESViewer es_gui.py

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/es-viewer.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}