# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

name: Publish Python Package to PyPI

permissions:
  id-token: write
  contents: read

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      # This step checks out a copy of your repository.

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
      # This step sets up a Python environment for the subsequent steps.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
      # This step installs the necessary build and upload tools.

    - name: Build package
      run: python setup.py sdist bdist_wheel
      # This step runs the setup.py script to build the source distribution and wheel.

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
      # This step uses a dedicated GitHub Action to publish the package to PyPI.
      # It uses an API token stored as a secret in the repository settings.
